### ISSUE TITLE
add tags

### ISSUE THREAD

**Issue by mikelmaron** [osmlab/basket#2]

**Comment by CmdrKerfy** [comment]
Tags are part of article posts. When clicked, it links to this page: http://osmlab.github.io/basket/tags/#Case Study

Would it be better if it was shown on the index as well?

**Comment by d3netxer** [comment]
It would be interesting if the tags were shown on each article on the article page.

**Comment by wuhland** [comment]
Started the job of getting tags in search results. Something strange that I could use some eyes on. If you type search into the search bar you will notice that the tags disapear and ##TAGS## replace them. 

##TAGS ## is supposed to be the placemarker where the correct tag html is injected from the search results. Here is the template: 

```
<script type="text/x-template" id="search-result">
  <li><article>
    <a href="##Url##">##Title## <span class="entry-date">##Date##</span><span class="excerpt">##Excerpt##</span></a><span class="entry-tags">##Tags##</span>
  </article></li>
</script>
```

Something close the correct tag html is being generated in the search results by search.js. 

```
  <li><article><a href="//osmlab.github.io/basket/articles/Ebola-GIS/">GIS Support for the MSF Ebola response in Guinea <span class="entry-date"><time datetime="2014-07-01T00:00:00+00:00">July 01, 2014</time></span> <span class="excerpt">A case study created by MSF highlighting the use of GIS during the Ebola response in Guinea.</span></a><span><a href="//osmlab.github.io/basket/tags/#Ebola" title="Posts tagged Ebola">Ebola</a>&nbsp;&bull;&nbsp;<a href="//osmlab.github.io/basket/tags/#Guinea" title="Posts tagged Guinea">Guinea</a>&nbsp;&bull;&nbsp;<a href="//osmlab.github.io/basket/tags/#MSF" title="Posts tagged MSF">MSF</a>&nbsp;&bull;&nbsp;<a href="//osmlab.github.io/basket/tags/#Case Study" title="Posts tagged Case Study">Case Study</a>&nbsp;&bull;&nbsp;<a href="//osmlab.github.io/basket/tags/#GIS" title="Posts tagged GIS">GIS</a>&nbsp;&bull;&nbsp;<a href="//osmlab.github.io/basket/tags/#2014" title="Posts tagged 2014">2014</a></span></article></li>
```

For some reason its not injecting. Haven't figured out why yet, if anyone has any ideas would love to hear about it.

**Comment by d3netxer** [comment]
This took me awhile but I kept on editing the search.js and search/index.md files but nothing was changing. I finally figured out that in my local build when I clicked the search button it took me to the http://osmlab.github.io/ domain instead of my local host; so I wasn't seeing anything I was actually editing. 

I ended up adding a baseurl line in the config file and changing all of the site.url links in the repo to site.baseurl. This will preserve the links for a local build and when committing to http://osmlab.github.io/

I left off at the point where it returns the tags now. The tags need to be outputted one at a time though so it doesn't display commas. @wuhland I think you are getting there with your populateTags function in the search.js file. It would be nice to have the tags displayed with formatting similar to this:

![screen shot 2015-06-20 at 12 56 47 pm](https://cloud.githubusercontent.com/assets/2665840/8268234/d05d2522-174b-11e5-96a4-c0b3423402cb.png)

**Comment by wuhland** [comment]
Got tags working on search, now we just need to find the appropriate scss. I tried setting .entry-tags color:blue on page.scss but to no avail. Not sure where to edit the sass for this at the moment.

**Comment by wuhland** [comment]
tags work. going to leave this open for a bit in case anybody has comments.

**Comment by wuhland** [comment]
It would be cool if the tags were color coded although that might look a bit crazy with a bagillion tag types. Thoughts? Perhaps iterate over a few colors?

**Comment by vknoppkewetzel** [comment]
I'll see if I can find the code for that/write it 👏🏼 on my wayyyy

Enviado desde mi iPhone

**Comment by vknoppkewetzel** [comment]
eyo eyo, anyone know where the tags themselves are getting stored when someone adds them to their post (which file? if such a file exists?). Need to take a look at it to see how I would then color code them

**Comment by d3netxer** [comment]
I think the tags look fine the way they are now. I'll close the issue.
